# Generated by Django 5.1.7 on 2025-03-12 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('A', 'American Home Food Products'), ('G', 'General Mills'), ('K', 'Kelloggs'), ('N', 'Nabisco'), ('P', 'Post'), ('Q', 'Quaker Oats'), ('R', 'Ralston Purina')], max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThermalType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('C', 'Cold'), ('H', 'Hot')], default='C', max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cereal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('calories', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('fiber', models.FloatField()),
                ('carbo', models.FloatField()),
                ('sugars', models.IntegerField()),
                ('potass', models.IntegerField()),
                ('vitamins', models.IntegerField()),
                ('shelf', models.IntegerField()),
                ('weight', models.FloatField()),
                ('cups', models.FloatField()),
                ('rating', models.CharField(max_length=255)),
                ('mfr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal_api.manufacturer')),
                ('thermal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal_api.thermaltype')),
            ],
        ),
    ]
