# Generated by Django 5.1.7 on 2025-03-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
